version: '1.0'

stages:
- build
- test
- report
- push
- deploy

steps:
  BuildingDockerImage:
    title: Building Docker Image
    type: build
    stage: build
    image_name: johnrtipton/flasktempconversion
    working_directory: ./
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}'
    dockerfile: Dockerfile
    build_args:
      - COMMIT_SHA=${{CF_SHORT_REVISION}}
      - COMMIT_BRANCH=${{CF_BRANCH_TAG_NORMALIZED}}

  ParallelTests:
    title: Running Tests
    type: parallel
    stage: test
    success_criteria:
      steps:
        only:
          - RunUnitTest
    steps:
      RunUnitTest:
        title: Run Unit Test
        image: ${{BuildingDockerImage}}
        commands:
          - pip install pytest coverage allure-pytest
          - coverage run -m pytest --alluredir=$CF_VOLUME_PATH/allure-results
          - coverage report
          - coverage html -d $CF_VOLUME_PATH/coverage
      LintTest:
        title: Run Lint Checks
        image: ${{BuildingDockerImage}}
        commands:
          - pip install pytest pylama pylama_pylint
          - pytest --pylama

  UnitTestReporting:
    title: Generate test reporting
    image: codefresh/cf-docker-test-reporting
    stage: report
    working_directory: '${{CF_VOLUME_PATH}}/'
    environment:
      - BUCKET_NAME=test-reports.trylinux.org
      - CF_STORAGE_INTEGRATION=report_bucket
      - REPORT_DIR.0=coverage
      - REPORT_INDEX_FILE.0=index.html
      - REPORT_TYPE.0=coverage
      - ALLURE_DIR.1=allure-results
      - REPORT_TYPE.1=allure

  PushingToECR:
    type: push
    stage: push
    title: Pusing to ECR
    candidate: ${{BuildingDockerImage}}
    tags:
    - latest
    - '${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}'
    image_name: myapp_dev
    fail_fast: false
    registry: ecr

  DeployToECS:
    title: Deploying to ECS
    stage: deploy
    image: ${{BuildingDockerImage}}
    commands:
      - cd deploy
      - pip install -r requirements.txt
      - python ecs-deploy.py deploy --cluster=fargate --service=myapp_dev --image=226671803964.dkr.ecr.us-east-1.amazonaws.com/myapp_dev:${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}